# Generated by Django 5.1.1 on 2024-11-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_customuser_nickname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
