# Generated by Django 5.1.1 on 2024-11-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_applicationhistory_role_and_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhistory',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
