# Generated by Django 5.1.1 on 2024-11-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_assigned_admin_application_is_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='assigned_admin',
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Назначено администратору'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_priority_assigned',
            field=models.BooleanField(default=False, verbose_name='Заявка назначена'),
        ),
    ]
