# Generated by Django 5.1.1 on 2024-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_application_assigned_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_priority_assigned',
            field=models.BooleanField(default=False, verbose_name='Заявка назначена'),
        ),
    ]
