# Generated by Django 5.1.1 on 2024-11-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_manager_is_priority_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
