# Generated by Django 5.1.1 on 2024-11-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_remove_customuser_full_name_application_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/images/'),
        ),
    ]
