# Generated by Django 5.1.1 on 2024-11-25 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_category_alter_application_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.category', verbose_name='Категория заявки'),
        ),
    ]
