# Generated by Django 5.1.1 on 2024-11-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_application_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_priority',
            field=models.BooleanField(default=True, verbose_name='Приоритетная заявка'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_priority_assigned',
            field=models.BooleanField(default=True, verbose_name='Заявка назначена'),
        ),
    ]
